### PR TITLE
Plotting improvements and bug fixes

### PR DESCRIPTION
**Pull request by mgiammar**

### CODE REVIEW

**Comment by deepanshs** [comment]
@mgiammar The figure title is clipped/not visible for almost all 1D methods.

**Comment by deepanshs** [comment]
@mgiammar Instead of pushing the title up, can you bring the spectral dimension labels inside the green box? Will this create a problem in multi-event spectral dimensions?

**Comment by mgiammar** [comment]
> @mgiammar Instead of pushing the title up, can you bring the spectral dimension labels inside the green box? Will this create a problem in multi-event spectral dimensions?

This seems like a good solution. Multi-event spectral dimensions have their labels in the center of the box so there shouldn't be any problems there. 
The only issue is it may cause some confusion between what represents a spectral dimension and an event. Maybe italicizing/bolding spectral_dimension labels will help?

**Comment by deepanshs** [comment]
@mgiammar Try the bold/italic font style and see how it looks in a multi-event method. An alternative may be to create another row in the grid plots just for the spectral dimension label. What are your thoughts?

**Review by deepanshs — APPROVED** [review]

**Pull request merged**
